layer.conf: customize config file version error messages
The default error message when a config file cannot be updated uses a
shell wildcard pattern which happens to be ambiguous in the ostro-os
combined repository:

   Exception: NotImplementedError: Your version of bblayers.conf has the wrong LCONF_VERSION (has 7, expecting 8).
   Please compare your file against bblayers.conf.sample and merge any changes before continuing.
   "meld conf/bblayers.conf .../meta*/conf/bblayers.conf.sample"

   is a good way to visualise the changes.

With this change, the proposed shell command will correctly pick the
conf file samples under meta-ostro. We could also customize the diff
tool; for now, the default "meld" is kept.

Depends on getting "sanity.bbclass: allow customizing config file
update error messages" merged into OE-core.

Signed-off-by: Patrick Ohly <patrick.ohly@intel.com>