ostro_security_flags.inc: exception for OpenJDK
Recent OpenJDK changes (meta-java 33ddb28) changed the compile flags
handling so that SECURITY_CFLAGS now really get used (as part of the
CFLAGS) everywhere. As a result, linking some shared objects fails
because -pie gets added after -shared, resulting in an attempt to
produce a binary instead of a shared object:

/usr/src/debug/glibc/2.24-r0/git/csu/../sysdeps/x86_64/start.S:104: undefined reference to `main'
collect2: error: ld returned 1 exit status
make[6]: *** [jdk8u-e8bed1496ff2/hotspot/make/linux/makefiles/jsig.make:56:libjsig.so] Error 1

The workaround is to not use the extra "-pie -fpie" flags for OpenJDK.

Signed-off-by: Patrick Ohly <patrick.ohly@intel.com>